const movieList= [{"id":1,"name":"Woman in the Moon (By Rocket to the Moon) (Frau im Mond)","genre":"Comedy|Drama|Romance|Sci-Fi","yearPublished":2001,"isInTheatres":true},
{"id":2,"name":"One Mile Away","genre":"Documentary","yearPublished":1998,"isInTheatres":true},
{"id":3,"name":"Ego","genre":"Drama","yearPublished":1997,"isInTheatres":false},
{"id":4,"name":"Joker Is Wild, The (All the Way)","genre":"Drama|Musical","yearPublished":1979,"isInTheatres":false},
{"id":5,"name":"Boxer, The","genre":"Drama|Thriller","yearPublished":1984,"isInTheatres":false},
{"id":6,"name":"Rabbit Test","genre":"Comedy","yearPublished":2007,"isInTheatres":true},
{"id":7,"name":"Idiot's Delight","genre":"Comedy|Drama","yearPublished":2007,"isInTheatres":true},
{"id":8,"name":"Cat and the Canary, The","genre":"Comedy|Horror|Mystery","yearPublished":2012,"isInTheatres":true},
{"id":9,"name":"Head in the Clouds","genre":"Drama|Romance|War","yearPublished":2005,"isInTheatres":true},
{"id":10,"name":"Rookie, The","genre":"Action|Comedy|Thriller","yearPublished":1993,"isInTheatres":true},
{"id":11,"name":"Hungry Hill","genre":"Drama","yearPublished":2006,"isInTheatres":false},
{"id":12,"name":"Boogeyman, The","genre":"Horror","yearPublished":2003,"isInTheatres":false},
{"id":13,"name":"Love's Kitchen","genre":"Comedy|Drama|Romance","yearPublished":2007,"isInTheatres":false},
{"id":14,"name":"There's No Business Like Show Business","genre":"Musical","yearPublished":1999,"isInTheatres":true},
{"id":15,"name":"Repo Men","genre":"Action|Sci-Fi|Thriller","yearPublished":2009,"isInTheatres":false},
{"id":16,"name":"Too Shy to Try (Je suis timide... mais je me soigne)","genre":"Comedy","yearPublished":1993,"isInTheatres":true},
{"id":17,"name":"Marwencol","genre":"Documentary","yearPublished":2002,"isInTheatres":false},
{"id":18,"name":"Dead Heat on a Merry-Go-Round","genre":"Comedy|Crime","yearPublished":2001,"isInTheatres":true},
{"id":19,"name":"Ballad of Jack and Rose, The","genre":"Drama","yearPublished":2006,"isInTheatres":true},
{"id":20,"name":"Wishing Stairs (Yeogo goedam 3: Yeowoo gyedan)","genre":"Drama|Horror","yearPublished":2003,"isInTheatres":false},
{"id":21,"name":"Barbarian Invasions, The (Les invasions barbares)","genre":"Comedy|Crime|Drama|Mystery|Romance","yearPublished":2009,"isInTheatres":false},
{"id":22,"name":"The Floating Castle","genre":"Comedy|Drama","yearPublished":1997,"isInTheatres":false},
{"id":23,"name":"The Last Wagon","genre":"Action|Adventure|Drama|Western","yearPublished":2002,"isInTheatres":false},
{"id":24,"name":"Confidentially Connie","genre":"Children|Comedy","yearPublished":2004,"isInTheatres":false},
{"id":25,"name":"3 Penny Opera, The (Threepenny Opera, The) (3 Groschen-Oper, Die)","genre":"Crime|Musical","yearPublished":1985,"isInTheatres":false},
{"id":26,"name":"Sea Hawk, The","genre":"Adventure|Drama|Romance","yearPublished":2006,"isInTheatres":true},
{"id":27,"name":"Arthur","genre":"Comedy|Romance","yearPublished":1993,"isInTheatres":true},
{"id":28,"name":"Foxy Brown","genre":"Action|Crime|Drama","yearPublished":2009,"isInTheatres":true},
{"id":29,"name":"Captain America: The First Avenger","genre":"Action|Adventure|Sci-Fi|Thriller|War","yearPublished":2001,"isInTheatres":true},
{"id":30,"name":"Secret of NIMH, The","genre":"Adventure|Animation|Children|Drama","yearPublished":1985,"isInTheatres":false}]

module.exports= { movieList }